-- MariaDB dump 10.19-11.0.2-MariaDB, for osx10.18 (arm64)
--
-- Host: localhost    Database: bdecsrennes
-- ------------------------------------------------------
-- Server version	11.0.2-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `categorie`
--

DROP TABLE IF EXISTS `categorie`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `categorie` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `categorie` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `categorie`
--

LOCK TABLES `categorie` WRITE;
/*!40000 ALTER TABLE `categorie` DISABLE KEYS */;
INSERT INTO `categorie` VALUES
(1,'P25');
/*!40000 ALTER TABLE `categorie` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `temoignages`
--

DROP TABLE IF EXISTS `temoignages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `temoignages` (
  `id` varchar(100) NOT NULL,
  `nom` varchar(50) DEFAULT NULL,
  `mail` varchar(100) DEFAULT NULL,
  `tel` varchar(30) DEFAULT NULL,
  `beContacted` int(11) DEFAULT NULL,
  `title` varchar(200) DEFAULT NULL,
  `descMission` text DEFAULT NULL,
  `wanted` int(11) DEFAULT NULL,
  `ambiance` text DEFAULT NULL,
  `whereFinded` varchar(255) DEFAULT NULL,
  `salaire` text DEFAULT NULL,
  `mobilite` varchar(200) DEFAULT NULL,
  `localisation` varchar(200) DEFAULT NULL,
  `logementEnt` varchar(200) DEFAULT NULL,
  `websiteJob` varchar(200) DEFAULT NULL,
  `conseil` text DEFAULT NULL,
  `categorie` varchar(5) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `temoignages`
--

LOCK TABLES `temoignages` WRITE;
/*!40000 ALTER TABLE `temoignages` DISABLE KEYS */;
INSERT INTO `temoignages` VALUES
('0245064a-0490-42d2-8950-77ae22bcf5a3','Clarisse Debray','clarisse.debray@student-cs.fr ','0682877740',1,'Y’avait pas d’offre ','Resolution de problèmes données par les différentes entités du groupe via des modèles mathématiques.\n(Ex le marketing de X veut des profils types pour pouvoir mieux cibler les annonces je les sors via analyse statistique/algorithme de clustering)',1,'Ça dépend des jours ','Forum alternants','Carte ticket resto (25€/j)\nChèque vacances \nFlexibilité des horaires \n2j de TT','Oui mais vazi faut forcer','Lille (Villeneuve d’ascq)','Deuxième appartement à coté de l\'entreprise','Jsp ','Bien bosser sur le forum et c’est tranquille ','P25','Cofidis group (synergie)'),
('2ed2254b-73c9-4379-a5ef-4112bc990cd6','Nicolas Massabie','nicolas.massabie@gmail.com','0640992161',1,'Ingénieur Digitalisation de la Certification ','Je suis dans le service méthode et support de la certif.\nJe bosse sur un projet européen où on cherche avec d\'autres entreprises aéronautiques comment améliorer les outils d\'échanges d\'information entre les parties prenantes de la certif (suppliers, OEM, authorities). Surtout de la recherche donc.\nSinon je fais aussi de la certif de fiche de modif avion (mais ça c\'est bonus).\nEt je fais des améliorations sur les process et outils de la certif en interne pour que tout se passe bien (SharePoint, bases de données)',1,'Ok+\nQue des darons avec moi donc parfois je me sens un peu à part. Mais globalement ça va.','LinkedIn','\"1550€ brut/mois. Cantine en partie subventionnée. \nCEE : 780€ de subventions vacances par an. 600€ de chèques vacances par an pour 180€ d\'apport. 220€ de subvention billetterie par an.\n8 semaines de congés.\"','Dassault ne propose rien. Faut trouver tout seul. (Piste filiale Dassault Falcon Jet USA).','Mérignac, 33','Famille (tante/oncle)','Tu tapes sur internet mdr','\"CONSEIL DE FOU : Ajoute tous les mecs qui ont fait CS dans les entreprises qui t\'intéressent. Puis tu postes ton CV une semaine plus tard. J\'ai trouvé comme ça.\"','P25','Dassault Aviation'),
('52365394-4c18-4a58-b376-8a60ef689ad2','Jeanne Marquet','Jeanne.Marquet@student-cs.fr','0667035059',1,'Data Analyst','- Dashboard (tableaux de bord) : pour différents services afin qu’ils puissent visualiser leurs données sur des graphiques ou des tableaux (activité, coûts, stocks etc.) \n- Organisation des données : je ne construis pas la BDD mais je dois restructurer les données que je vais utiliser (jointures etc.) \n- Calculs sur les données : création d’un modèle de proba pour la disponibilité des pièces, calcul statistique de la durée de vie des pièces \n- Rencontre avec les utilisateurs : réunions pour définir le cahier des charges, documentation etc. ',1,'Je travaille dans une petite équipe, le service transverse, il y a beaucoup d’alternants dans ce service. \nIl y a plus de 5000 personnes sur le site. \nLes différents services ont un budget pour organiser des repas d’équipe de temps en temps. ','Site d\'offres d\'emplois de l\'entreprise','1100€ par mois environ \n50 à 100€ de prime pour l’atteinte des objectifs au niveau de l’usine par mois\nRepas très peu cher à la cantine (très bonne et avec beaucoup de choix), déduit du salaire du mois suivant (pour moins de 3€ on peut avoir un steak avec l’accompagnement et un dessert par exemple) ','Sûrement sur le site d’Agrate près de Milan. (beaucoup de lieu possible dans le monde)','Crolles (près de Grenoble)','Deuxième appartement à coté de l\'entreprise','https://www.st.com/content/st_com/en/about/careers.html','Restez ouverts ! Des domaines auxquels vous n’avez peut-être pas pensé pourraient aussi correspondre à vos attentes en terme de travail, ça vaut le coup de regarder, il y a beaucoup de métiers qu’on n’imagine pas.','P25','STMicroelectronics - Site de Crolles '),
('5911a92e-4ada-4f01-9c1f-efaa8ef85e06','Safran Data Systems - Groupe Safran','axel.danieau@gmail.com','0786762667',1,'Apprenti Ingénieur Méthodes Industrielles/Usine 4.0','- Rédaction de procédures de fabrication et de traçabilité de nos produits (5% de mon temps)\n- Développements de macros VBA d\'automatisation de tâches pour différents services en production (15% de mon temps)\n- Développement de solution numérique dans le cadre de la feuille de route Usine 4.0 (10% de mon temps)\n- Gestion de projets en amélioration continue (5S, Management Visuel, DMAIC, Brainstormings) (70% de mon temps)\n',1,'Très bon ambiance dans le service (~25 personnes), moyenne d\'âge de 26/27 ans, 2 apprentis dans l\'équipe, After work réguliers, Restaurants réguliers le midi','Forum alternants','Première année : 960€ \nDeuxième année : 1350€ (dont l\'augmentation des 21 ans)\nTroisième année : 1500€\n\n25 jours de Congés Payés\n5 jours de RTT (dont 3 RTT employeurs)\n13e mois\nIntéressement/Participation/Abondement\nRestaurant d\'entreprise (pas de tickets restaurant)\nPointage des horaires de présence (plus de jours de congés en tant que rattrapage des heures sup)\nCSE avec subvention de 40€/trimestre (c\'est peu)\nMobilités internes facilitées une fois rentré dans le groupe Safran','Pas de bonnes relations avec les sites à l\'étranger --> C\'est à moi de trouver un stage de 12 semaines à l\'étranger (groupe Safran ou ailleurs). Les RH m\'aideront à faire les papiers, etc','ZA Courtaboeuf - Les Ulis (91) (10min en voiture du campus de Gif)','AirBnB dans le 78 ou le 91 loué 1 mois sur 2 (~1000€/mois loué -> 500€/mois lissé sur l\'année)','https://www.safran-group.com/fr/offres?companies%5B0%5D=609-safran-data-systems&contracts%5B0%5D=39-alternance&sort=relevance','\"En région parisienne pour avoir un logement bien équipé je conseille de prendre un AirBnb 1 mois sur 2 (le gain d\'APL en cas de double logement étant très faible ca devient rentable). J\'ai commencé ma recherche d\'entreprise en aout via les sites recrutements/carreers des entreprises qui m\'intéressaient ou via Linkedin -> J\'ai eu que 1 entretien sur 30 entreprises contactées (qui m\'a accepté). Au final, à la rentrée je n\'avais pas accepté définitivement pour attendre le forum apprentissage CentraleSupélec. Au forum, j\'ai été retenu par 2 entreprises (dont Safran) en génie Industriel. J\'ai donc choisi Safran pour les missions et la localisation (même si moins bien payé). Trouver une alternance en aout/septembre n\'est pas facile, il ne reste pas beaucoup d\'offres disponibles donc il faut pas forcément faire les difficiles, vous ne pourrez pas avoir toutes les cases de cochées (missions, salaires, correspondance avec vos valeurs, ambiance, avantages, etc). A vous de placer vos priorités !\"','P25','Safran Data Systems - Groupe Safran'),
('5af65e05-741d-4b3f-8cce-67779bcb67ee','Mathias Polverino','polverinomathias@gmail.com','0642214500',1,'Apprenti ingénieur pour la validation par la simulation','Intermédiaire entre physicien (modèle physique) et électronicien (circuit électronique) du laboratoire. Un mélange de physique, d\'électronique et d\'informatique.',1,'Excellente, des jeunes et des moins jeunes, vraiment bienveillante','Envoi direct au labo','1245€ 1ere année, 1700€ en 3ème + primes\n\nPas de télétravail (Secret Défense SD)\n\nÉnormément de vacances ! Au moins 8 semaines en première année, autour de 10 en 2ème\n\nLignes de bus privées partout en Île de France qui mènent au centre (ultra pratique et gratuit)\n\nCantine bonne et pas chère (2€70/repas)\n\nATTENTION POSTE SD, donc nationalité française et parents français obligatoirement. Soumis au secret, c\'est parfois contraignant si vous avez des questions hésitez pas','Statut SD, donc Casa (vous pouvez chercher par vous même une autre boîte pour aller à l\'étranger mais c\'est à vous de chercher ducoup)','Ile de france','Deuxième appartement à coté de l\'entreprise','CEA DAM','Prenez vous y tôt sinon vous risquez de vous retrouver avec qqchse que vous aimez pas (pour la même raison acceptez pas le premier truc qui vient, prenez le temps de chercher...)','P25','CEA DAM'),
('6a90df05-fc43-451d-ae19-721728275f2e','Nicolas Goyard','nicolas.goyard@student-cs.fr','0672830038',1,'Ingénieur d\'étude électrique','Dessin de plans de réseaux dans les bâtiments (électricité, plomberie, aération), et schémas d\'armoires électriques',1,'L\'ambiance est bonne, c\'est un petit bureau d\'étude avec une dizaine d\'employés seulement, il y a beaucoup d\'entraide et on plaisante bien pendant les pauses.','J\'ai tapé bureau d\'étude sur google maps (dans la région où je souhaitais du coup), et j\'ai appelé les numéros que j\'ai trouvés.','Carte resto (tickets resto mais sur une carte bancaire), comité d\'entreprise','Je vais faire le semestre académique à Casa car mon entreprise ne travaille pas à l\'international.','Lyon','Chez des amis','https://inrecruitingfr.intervieweb.it/groupemoos/fr/career (c\'est le site d\'offres d\'emplois concernant tout le groupe auquel l\'entreprise appartient, elle y dépose parfois des offres)','C\'est une bonne idée d\'arriver au moins avec des pistes pour un contrat à la rentrée, mais sachez que l\'école vous donnera également accès à des opportunités intéressantes donc ne vous précipitez pas. Privilégiez un lieu qui ne nécessitera pas de louer un deuxième logement (proche de l\'école ou de votre famille), ça permet des grosses économies. Et tenez vous informés durant l\'été, l\'école fera sûrement passer des infos avant la rentrée.','P25','BEEM Lyon'),
('712c81f0-9fbf-4229-89dd-e941a3e39073','Mouad Zeroual ','mouad.zeroual@student-cs.fr','0650804621',1,'Développeur full stack ','Comprendre la modélisation de la solution proposée (les différentes entités, liens entre les entités, l\'utilité de chaque information recueillie...) pour pouvoir proposer, si nécessaire, des corrections/ modifications ou des améliorations possibles de certaines parties. \nConstruire le modèle correspondant à cette modélisation dans la plateforme (du JavaScript essentiellement)',1,'Petite équipe.\nBonne ambiance de travail.','Site d\'offres d\'emplois','1321€/M + 9€/J tickets restaurant ','Dispensé ','La défense ','Chez les parents','https://keenpoint.com/careers/','','P25','Keenpoint consulting '),
('802f94f2-568c-4901-8946-63292c320408','Pierre Bouquin','pierre.bouquin@student-cs.fr','0668639998',1,'Expert en efficacité énergétique','Mon équipe réalise des audits d\'optimisation énergétique, les experts vont sur des sites qu\'ils soient tertiaires ou industriels et trouvent des mesures de conservation d\'énergie. L\'objectif est d\'optimiser les dépenses énérgétiques des clients ainsi que de réduire leurs émissions de CO2. \nConcretement on se déplace dans l\'usine du client, on fait un tour précis de la production afin d\'en comprendre le fonctionnement, on visite aussi les utilitaires (chaudières, compresseurs, production d\'eau froide...) et ensuite on fait des calculs de gain sur les opportunités trouvées. On fait ensuite un compte rendu au client, avec des propositions de plan d\'action en fonction des différentes mesures de conservation d\'énergie trouvées. \n\nMon role la dedans est d\'accompagner les experts dans leur audit, en faisant du traitement de données de consommation, en amont de la visite, pour leur faciliter la tache. \nEn tache de fond je développe aussi des outils qui permettent d\'accélerer le travail de mes collègues. ',1,'On est dans un open space avec d\'autres équipes qui sont hyper jeunes qui travaillent dans la même grande division. Mon équipe est chill et en plus ils prennent 2 stagiaires par an donc c\'est cool. Par contre je suis le 1er et seul alternant. Mon boss est super cool, pas prise de tête et même si très occupé disponible si j\'ai des questions. ','Réseau personnel','Salaire avant 21 ans : 1150€/mois\nSalaire après 21 ans : 1360€/mois\nSalaire 3ème année : 1650€/mois\nCE : 1200€/an\nParticipation intéressement : (pas la première année) mais sinon à peu près 1000euros/ an sous la forme d\'action Schneider\n5 semaines de CP /an\n8 jours RTT / an','Mobilité réalisée en entreprise lors d\'audits à l\'étranger','Rueil Malmaison (banlieue parisienne, direct en RER A)','Chez les parents','https://careers.se.com/global/jobs?lang=fr-FR&sortBy=relevance&page=1','','P25','Schneider-Electric '),
('90fb194b-3f30-46a6-82d2-17c3ad2b3280','Théo COrcia','Theo.corcia@student-cs.fr','0647357719',1,'Ingénieur en télécommunications et data analyste ','Codage python et analyse de reporting ',1,'Mon équipe est cool j ai pas eu de problème pour m’intégrer','Réseau personnel','1150 en premier année / navigo remboursé / ticket restaurant/ 2 jours de télétravail par semaine','Centrale Casablanca ','Velizy','Chez les parents','Linkedin ou plateforme sfr ','Pas se prendre la tête, faire jouer son réseau personnel et répondre à des annonces sur internet, et sinon tout donner au forum (si tu le fais sérieusement on a facilement au moins 3 offres d alternance sur)','P25','SFR'),
('a69eb208-cb5a-42c1-bb83-c9ca8160bc62','Anonyme','','',0,'Apprenti ingénieur logiciel','Je crée des procédures de test automatisé pour divers projets.',0,'Correct, il y a un mix de jeunes et de vieux. Si j\'ai besoin de renseignement, je trouve toujours quelqu\'un en mesure de me renseigner. Des activités en dehors du travail sont organisées, comme des restos et de l\'escalade.','Site d\'offres d\'emplois de l\'entreprise','1 243€','','Massy-Palaiseau ','Chez les parents','https://www.safran-group.com/fr/offres','','P25','Safran'),
('b14d9efd-2000-41c2-8f5d-6282cb491bbd','Alexis CHATAIL--RIGOLLEAU ','alexis.chatail-rigolleau@student-cs.fr','0782596630',1,'Apprenti développement informatique ','Tout est fait en C++.\n\n- Développement d\'un logiciel shell : Parsing et affichage de fichier logs de machines d\'enregistrement de signaux télémétriques Safran. (Facile, en vrai c\'est du C, pas du C++, utile pour le SAV de Safran Data)\n\n- Linux PTP : test de l\'utilisation potentielle du protocole PTP pour communiquer de façon super rapide entre les machines de Safran Data Systems (longs tests sur machine très intéressants, j\'ai pété une carte réseau à 3000€)\n\n- Scheduling RSR (machine d\'enregistrement de signaux télémétriques) : Implémentation d\'un plugin de planification d\'enregistrement à l\'avance, travail sur l\'interface homme-machine.\n(Super bien, très intéressant)\n\n- Développement d\'une fonctionnalité pour l\'outil BSS (Best Source Selector : sélection dynamique du meilleur signal selon des critères de ratio signal sur bruit) : ajout d\'un système de communication du pauvre, pour les clients qui ont pas la thune pour payer des émetteurs de dernière génération, et aussi afin d\'assurer la rétro compatibilité de la machine . (Trop bien, demandé par des clients américains et pakistanais depuis 2 ans, ',1,'Chill, pas de pression, open Space avec des blagues de cul tout le temps','Forum alternants','950 / 1100 / 1350','Par moi même, parce que j\'avais pas envie d\'aller en Allemagne ','Les Ulis ','Deuxième appartement à coté de l\'entreprise','https://www.safran-group.com/fr','Période d\'école= période de repos','P25','Safran Data Systems '),
('b9161ec5-5ef8-4043-b480-f177305769f7','Ruben Ramdewor','ramdewor.ruben@gmail.com','0612697704',1,'Ingénieur méthodes maintenance','Mon rôle en tant qu\'alternant est celui de chef de projet sur un projet d\'automatisation d\'une ligne industrielle. Je suis responsable de la gestion des relations avec les fournisseurs ainsi que de la partie technique du projet. Mes missions sur ce projet sont très variées et ne sont pas répétitives. De plus, j\'ai également un autre projet majeur axé sur la numérisation de la maintenance. Si vous êtes intéressé par une alternance dans le monde industriel, n\'hésitez pas à me contacter. Je serai en mesure de fournir plus de détails sur mes missions et de répondre à vos questions.',1,'C\'est l\'usine donc l\'ambiance est plutot très cool ','Forum alternants','1100 euros en première année avec un bon CE et le deuxième logement payé par l\'employeur.','La mobilité à l\'étranger ce fait sous forme de stage à l\'étranger pris en charge pas l\'entreprise ','Périphérie large de grenoble ','Deuxième appartement à coté de l\'entreprise','https://www.se.com/fr/fr/about-us/careers/students-young-professionals.jsp','','P25','Schneider Electric '),
('c53b4d84-2a4e-45d3-9801-f5abdaca6f95','Dylan Pontaillier','dylan.pontaillier@student-cs.fr','628045657',1,'Apprenti chef de projet client','Je réalise quelques tâches par ci, par là en assistance d\'un chef de projet car étant donné que je ne suis pas là tout le temps, je ne peux pas vraiment gérer des projets entiers de A à Z. De plus, les missions sont très variées mais globalement je réalise les choses suivantes :\n- Réalisation de design de templates d\'affichage d\'étiquettes électroniques\n- Un peu de programmation pour faciliter le travail de l\'équipe \n- Beaucoup de taches spécifiques à l\'entreprise (Si vous me contactez, je vous expliquerai beaucoup plus en détail)',1,'L\'ambiance de travail est très sympa. Notre équipe est globalement jeune et nous avons une très bonne entente entre nous. Tout le monde est super cool !','Forum alternants','1200€/mois ','Il est possible d\'aller un peu partout dans le monde avec cette entreprise (Pays-Bas, Suède, Espagne, RépubliqueTchèque...).','Nanterre (92)','Chez les parents','Les offres sont surtout sur leur LinkedIn','','','SES-Imagotag'),
('d7144fdd-7361-4319-a70f-ad2dc9eefe02','Fabien Joao','fabien.joao@student-cs.fr','0767750684',1,'Chargé d\'études actuarielles','Concrètement le début de l\'alternance consiste dans un premier temps à se familiariser avec le milieu et les termes spécifiques de l\'assurance. Cela c\'est fait pour ma part lors de ma mission de programmation où j\'ai manipulé des chiffres d\'affaires de différentes entités du groupe afin de les comparer à des estimations réaliser au cours de l\'année. J\'ai pu également manipuler des indicateurs financiers de l\'assurance comme le ration sinistres payés/primes reçues des cotisants. Je fais aussi beaucoup de manipulation excel sur des projections sur les années futures concernant différentes donnée (CA, Cotisations, Nombre de sinistrés..)\n\nL\'avantage de cette alternance est que c\'est une forme de graduate program où on tourne dans différentes équipes (6 au total) au sein de la DAF (Direction de l\'actuariat financier).',1,'L\'ambiance est très sympathique, il y a des jeunes avec lesquels interagir et les managers sont accessibles.','Forum alternants','1580','Mise à disposition dans une entreprise (car entreprise présente uniquement en France)','Malakoff Humanis','Chez les parents','https://carrieres.malakoffhumanis.com/offre-de-emploi/liste-offres.aspx','','P25','Malakoff Humanis'),
('d92bbed7-a4c3-4b04-b7bd-46e3911ab505','Baptiste Pariolleau','baptiste.pariolleau@student-cs.fr','0621982675',1,'Ingénieur en bureau d\'études mécanique','Suivi de la conception d\'une structure sur les 3 ans, dans le cadre du développement d\'une fusée (prédimensionnement, dimensionnement, essais, réalisation/production, vol)\n\nCet été, mon stage opérateur est aux essais',1,'L\'ambiance est très bonne, tous les membres de l\'entreprise sont des passionnés qui n\'hésitent pas à répondre à mes questions.','Candidature spontannée en envoyant un mail au chef du secteur thermo-mécanique','Salaire : 1000€ en 1A, jusqu\'à 1900€ en 3A\n\nAvantages : le CE (pour le site de Brest, Biscarosse et St-Médard-en Jalle Issac) est assez bon (chèque vacance très subventionné, réduction sur des événements ...), très grand complexe sportif (site d\'Issac)','6 mois en Allemagne en 3A, au sein de l\'entreprise','Site de St-Médard-en-Jalle Issac (3 autres sites présent dans la région + 3 sites en région parisienne + un site à Brest + un site à Toulouse)','Chez les parents','https://arianegroup.wd3.myworkdayjobs.com/fr-FR/EXTERNALALL','Certes vous avez besoin de l\'entreprise pour avoir une alternance, mais l\'entreprise a aussi besoin de vous ! (sinon y\'aurait pas d\'offre d\'alternance) D\'autant plus que vous êtes des centraliens. Ne soyez pas gêné et n\'hésitez pas à aller vous vendre. Pour info, j\'ai envoyé un mail en candidature spontanée à ArianeGroup pour avoir mon alternance, et j\'ai appris plus tard que le chef de mon secteur (3e hiérarchique) cherchait spécifiquement un centralien, et je pense que ce n\'est pas le seul comme ça.  Bon courage pour votre recherche !','P25','ArianeGroup'),
('e2f57e24-9629-4063-8f3f-0e65a49a3449','Kamil Hammani','kamil.hammani@student-cs.fr','0781882457',1,'Chef de projet client','Meetings avec des clients en langues étrangères ',1,'Incredible','Forum alternants','1200 0 avantages','Dubai, Suede ','La Défense ','Chez les parents','Site de SES Imagotag ','Pas se stresser le forum carry de fous','P25','Ses Imagotag '),
('f8649e45-dc94-42d2-99f5-8e51ce90932f','Raumin Valade','Raumin.valade@student-cs.fr','0635123100',1,'Ingénieur sécurité des systèmes d’informations ','Missions diverses sur la sécurité des systèmes d’information d’ArianeGroup. Plus précisément dans la cyber sécurité, je travail avec le SOC, la sécurité de la factory 4.0, le service juridique… ',1,'Très bonne ambiance de travail. Il y a beaucoup de cohésion et d’entraide. ','Site d\'offres d\'emplois de l\'entreprise','Environ 1000 euros en première année jusqu’à 1700 euros en troisième année avec de nombreuses primes, chèque vacances et CE. ','En Allemagne avec ArianeGroup et peut être à Kourou. ','Bordeaux ','Deuxième appartement à coté de l\'entreprise','https://www.ariane.group/fr/carrieres/','Ne pas attendre la rentrée pour postuler.','P25','ArianeGroup'),
('f87c031b-e16c-4f08-add7-733fab0895e3','Mattéo Lucas','matteo.lucas04@gmail.com','0695278819',1,'Alternant Open Innovation et Communication','Mes missions principales sont :\n- Trouver des startups intéressantes (recherches internet, salons, LinkedIn, ...)\n- Évaluer des startups \n- Améliorer des processus d\'open innovation (refonte de la base de données et mise en place d\'un outil, optimisation des moyens de sourcing, ...)',1,'L\'ambiance de travail chez Orano est top ! Nous sommes énormément de stagiaires et alternants. Par exemple tous les midi nous jouons au babyfoot et nous sortons boire des coups après le taf.','Forum alternants','- 1350€/mois +250€/mois si double logement\n- CE avec chèques vacances 750€ pour l\'été et 400€ de chèques cadeaux pour Noël \n- Télétravail 1 jour/semaine ','Normalement au Canada dans l\'ancienne entreprise d\'un de mes collègues.','Région parisienne ','Deuxième appartement à coté de l\'entreprise','https://www.orano.group/jobs/fr/nos-offres','Pour la recherche d\'entreprise je te conseille de ne pas être trop difficile de chercher très large et faire plein d\'entretiens pour prendre de l\'XP. Arrive en septembre avec ton CV et ta lettre de motivation. Au forum des alternants tu rencontreras plein d\'entreprise, c\'est le moment le plus important !  Si tu as besoin d\'un deuxième logement tu peux faire appel à des entreprises comme Via Humanis qui font tout pour toi (en plus c\'est gratuit)','P25','Orano');
/*!40000 ALTER TABLE `temoignages` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `test`
--

DROP TABLE IF EXISTS `test`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `nom` varchar(50) DEFAULT NULL,
  `prenom` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `test`
--

LOCK TABLES `test` WRITE;
/*!40000 ALTER TABLE `test` DISABLE KEYS */;
/*!40000 ALTER TABLE `test` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2023-07-26 22:24:14
